### ISSUE TITLE
Few user questions!

### ISSUE THREAD

**Issue by UANEMESIS** [glitchassassin/lackey#113]
Hi developers! Happy New Year!

I have few user questions:

1) How I can turn on logging to file?
My example:
from lackey import *
a = "C:\go.log"
DebugMaster.setLogFile(a)

Result:
    DebugMaster.setLogFile(a)
TypeError: setLogFile() missing 1 required positional argument: 'filepath'

2) Can I somehow set confidence? (lever of accuracy):

[info] Found match for pattern 'C:\Program Files (x86)\Python36-32\NinjaBot\head
er_of_platform.png' at (351,146) **with confidence** (0.9999997019767761). Target at
 (434,156)

in some cases I want to set different level of confidence.

**Comment by glitchassassin** [comment]
Happy New Year to you too!

The best resource for getting acquainted with the typical usage like this is the [SikuliX documentation](http://sikulix-2014.readthedocs.org/en/latest/index.html), as Lackey is intended to be a drop-in replacement.

First, DebugMaster is the uninstantiated class; what you're looking for is the Debug object:

    from lackey import *
    a = "C:\go.log"
    Debug.setLogFile(a)

For more details, check out the [log and debug messages documentation](http://sikulix-2014.readthedocs.io/en/latest/scripting.html?highlight=debug#debuglog).

Second, you absolutely can set the level of confidence for finding a pattern. This can be configured globally by changing `Settings.MinSimilarity`, or individually by passing a Pattern object instead of just the path.

By default, `Settings.MinSimilarity` is `0.7`. If you don't want to change this globally, you can set it individually by calling the pattern's `similar()` method:

    Settings.MinSimilarity = 0.8
    find("image_to_find.png") # Will only find matches with confidence 0.8 or greater
    find(Pattern("image_to_find.png").similar(0.9)) # Will only find matches with confidence 0.9 or greater

For more details, check out the [Pattern documentation](http://sikulix-2014.readthedocs.io/en/latest/pattern.html).

Hope this helps!

**Comment by UANEMESIS** [comment]
2nd - it works! Thank you!

1st > about DebugMaster...

I just want to write logging from cmd console (on windows) to file.
Please,, provide me instruction how I can write log information to file.

**Comment by glitchassassin** [comment]
I made one mistake in the snippet I provided above:

    from lackey import *
    a = "C:\\go.log"
    Debug.setLogFile(a)

Have to escape the backslashes in Python strings. Other than that, I've tested the above and it does write Lackey event logs to file.

Are you looking for something else?

**Comment by UANEMESIS** [comment]
Works with backslashes!!! Thank you! 

Have a nice day!
