### ISSUE TITLE
RDP Connection Prevents Windows-style Pop-ups Interaction

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#36]
This is a bit tricky to even explain - but it seems impossible to interact with a windows-style pop-up while there is active RDP (tried both with built-in RDP and VNC) to that machine.

Start script on machine A -> script works until need to click on a pop-up thrown by application and fails to recognize it. If there is no RDP connection to machine A, everything works as expected.

Do you know what might cause this kind of issue?

**Comment by glitchassassin** [comment]
Strange. Let's try some debugging steps.

If you catch the error and use SCREEN.capture() to save the screen to a temporary file, does the popup show up as expected?

**Comment by maxdule** [comment]
Good catch! No, capture() saves the screen without the pop-up, as it does not exist at all!

**Comment by glitchassassin** [comment]
Do you see the popup on the local screen for "machine A"?

Any additional details you can provide about the popup that might help identify the technical details behind the scenes?

**Comment by maxdule** [comment]
Yes, the pop-up is there all the time. Pop-up is actually a pop-up balloon (tool-tip) that pops up on some finished action and is of this [type](https://msdn.microsoft.com/en-us/library/system.windows.forms.tooltip(v=vs.110).aspx)

So, briefly:
1. I am remotely logged on machine A - script on machine A runs and capture() saves the screenshot where this pop-up balloon is not visible
2. I am not remotely logged on machine A - script on machine A runs and capture() saves the screenshot with the pop-up there

**Comment by glitchassassin** [comment]
I've managed to track down a couple similar reports, suggesting that we should pass the [CAPTUREBLT flag to the `BitBlt()` function](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183370(v=vs.85).aspx) in order to capture windows that are layered on top of the screen.

I've made this change in the `develop` branch. Can you help test this?

Clone the develop branch to your local machine, then use `pip install -e ./GitHub/lackey` (setting the path to the repo where setup.py is) to install the development version for Python.

Let me know what your results are and we'll go from there.

Thanks!

**Comment by maxdule** [comment]
Sure I can. I'll get back to you on Monday with the results.

**Comment by maxdule** [comment]
I've tested both the accessibility of previously problematic pop-ups, and the capture method. Everything seems to be working fine in develop. Good work!

**Comment by glitchassassin** [comment]
Great! Thanks for your help.

**Comment by glitchassassin** [comment]
Fixed in latest release.
