### ISSUE TITLE
Failed to import with python 3.5

### ISSUE THREAD

**Issue by efficks** [glitchassassin/lackey#40]
Lackey does not work with python 3 because Tkinter module is now named tkinter (lower case t).
Some classes from tkinter also get renamed.

**Comment by glitchassassin** [comment]
I'll review Python 3 compatibility across the board and add it to the AppVeyor build process.

**Comment by glitchassassin** [comment]
The Python wrapper for OpenCV ([opencv-python](https://pypi.python.org/pypi/opencv-python/3.1.0.3)) that we're currently using only seems to be built for Python 2.7 and 3.5 on Windows.

I've updated the `develop` ring for Python 3 compatibility, and it's passing the build tests in AppVeyor. I'll check to see if there's another way to import OpenCV that supports more platforms. Otherwise, 2.7 and 3.5 may be the only compatible versions for Windows at the moment.

**Comment by efficks** [comment]
@glitchassassin  Thank you.

**Comment by glitchassassin** [comment]
I've submitted a pull request for OpenCV to add Python 3.4 to its build process. I'll go ahead and roll a new Lackey release later this week

**Comment by glitchassassin** [comment]
Fixed with version 0.5.2 (just released to Pypi). 3.4 will be added when OpenCV-Python is updated.
