### ISSUE TITLE
inconsistant click locations in OCR branch

### ISSUE THREAD

**Issue by jwstolk** [glitchassassin/lackey#45]
Not doing OCR now, but I am still using the OCR branch.
The returned locations are not the middle of the found image.
I have been "correcting" today using targetOffset(), but I'm starting to see a pattern: If I mirror the incorrect location over a diagonal line starting at the top-left corner of the image, I end up in the centre of the image.

Could the X and Y offset within the image be swapped somewhere?
(I'm slowly getting more used to Pyhton. and still thinking about a faster OCR approach.)

**Comment by glitchassassin** [comment]
It might be that, or the "needle" width/height might be getting flipped. I'll take a look a bit later today.

**Comment by glitchassassin** [comment]
It does seem to have been the "needle" shape. It was provided as (height, width) rather than (width, height) as I expected. I was able to duplicate your results using an image higher than it was wide.

I reversed the `needle.shape` tuple, tested it again, and it seems to be fixed. I've pushed the fix to the OCR branch.

While I was at it, I updated the OCR branch to master. I had to make quite a few reconciliations in RegionMatching.py manually. My test suite shows that it seems to be working fine, but if you run into any issues, let me know.
