### ISSUE TITLE
lackey not handling non-core-windows applications properly

### ISSUE THREAD

**Issue by nefsal22** [glitchassassin/lackey#48]
Hi,
I am working on an open source project to automate FTK Imager application. I have started the work and found that Lackey is not allowing the script to press ALT button in the FTK imager application. Here, the FTK is focusing up as a new window.

from lackey import *
appname=App("FTK Imager")
appname.focus()
appWindow=App.focusedWindow
key1 = Key.ALT
p1 = PlatformManagerWindows()
p1.typeKeys(key1)

**Note: I am including only the logic to press ALT key here.

I have also found that the Lackey is not even focusing the MS word or MS Excel

Could you please guide me on this?

**Comment by glitchassassin** [comment]
Hi nefsal22,

The PlatformManager is an internal class, you don't need to instantiate it. To type keys, use the following code:

    from lackey import *
    appname = App("FTK Imager")
    appname.focus()
    type(Key.ALT)

I usually find it's easier to prototype with [SikuliX](http://sikulix.com/) (since it has a handy IDE) and then run the created script with Lackey. But it certainly should work either way! For more details on Sikuli script, check out [their documentation](http://sikulix-2014.readthedocs.io/en/latest/index.html).

If FTK Imager launches a Word or Excel document and it isn't focusing properly, you can try focusing the Word window the same way you focused FTK Imager:

    word_doc  = App("Microsoft Word")
    word_doc.focus()

Does this help?

**Comment by nefsal22** [comment]
Thanks for the reply! 

In fact, my code is working perfectly with Notepad and Skype applications. But I changed it as per your instruction and still getting the same response. 

FTK Imager is focusing properly but the ALT key function is not happening in the screen. I am running it through my DOS window and getting the below out.

Z:\>python test.py
[action] Typing '{ALT}' with modifiers 'None'

I have also checked the same code with MS Word and MS Excel, but the same issue is there.

**Comment by glitchassassin** [comment]
Hmm. A couple followup questions:

1. Does FTK Imager receive *any* keypresses from Lackey?
2. Are you trying to use ALT as part of a key combo (e.g., Alt+F to select the File menu)?
3. What do you get if you call `print(appname.isRunning())` on the App instance associated with FTK Imager, MS Word, and MS Excel respectively?

**Comment by nefsal22** [comment]
Sure!

1. The Lackey could only able to focus the FTM Imager App. I have tried F1(which is the help menu) too. But none of the clicks are working properly. 

2. Yes, I wanted to try ALT + F to get the options in the File menu. So that I can navigate and find the right option.

3. For all the app, I am getting a TRUE response for the isRunning() function. That's why I got clueless about why its not allowing to press ALT or F1 keys.

**Comment by glitchassassin** [comment]
Some applications hook keyboard events at a low level, possibly ignoring simulated keypresses. Usually those are video games, though, not regular Windows applications. Just in case, let's try a couple more things.

First: Instead of calling the low-level PlatformManager methods directly, you can [pass a KeyModifier to the type() function](http://doc.sikuli.org/keys.html):

    type("f", KeyModifier.ALT)

This holds the ALT key while typing "f".

Second: Note that there's a difference between `type("f")` and `type("F")`. the first types the "f" key, while the second holds shift and types the "f" key (to make it uppercase). So what your code actually sends is ALT+SHIFT+F, which might give you unexpected results in FTK Imager.

Third: If all that doesn't work, does the file menu pop up in FTK Imager when you *manually* key Alt+F?

Thanks!

**Comment by nefsal22** [comment]
I have already tried the keyModifier before and didn't make any difference in FTK. The FTK is not responding to the anyof the keyboard or mouse events.

And yes, the manual ALT is working with FTK. In fact all the all other shortcuts are working if I am manually doing it.(Like F1 or other ALT combinations)

**Comment by glitchassassin** [comment]
What version of Windows are you running?

**Comment by nefsal22** [comment]
Windows 10.

**Comment by glitchassassin** [comment]
Hmm. #49 also reports that some applications in Windows 10 are spotty in receiving events. These may be related. Let me see what I can dig up.

**Comment by glitchassassin** [comment]
Hi nefsal22,

Per the discussion in #49, can you try running your script as administrator and see if FTK receives the keyboard & mouse events properly?

**Comment by nefsal22** [comment]
Awesome! It is working  when I run Command Prompt as administrator :) 
So If I have to deploy my code in another system, I have to include the code to elevate the privilege right?

**Comment by glitchassassin** [comment]
Yes. If FTK Imager is running with admin rights, your script will have to run with admin rights as well.
