### ISSUE TITLE
Debug log file cannot be updated

### ISSUE THREAD

**Issue by jazz1215** [glitchassassin/lackey#72]
Hi,
Just found that the debug log file was opened in 'r' mode so could not be updated.
It could be fixed by open in 'a' mode.
Also the '\r' is preferred after the log_entry so that the output text file is friendly in Windows.
Below is my quick fix to get it work for reference.

File: Settings.py
Method: def _write_log(self, log_type, log_time, message):

`

        elif self._log_file:
            # Otherwise write to file, if a file has been specified
            with open(self._log_file, 'a') as logfile:
                logfile.write(log_entry + '\r')
        else:
            # Otherwise, print to STDOUT
            print(log_entry)`

**Comment by glitchassassin** [comment]
Good catch, thanks.

Note that Python 3 by default uses platform-appropriate line endings, so `\n` should always be used rather than `\r\n`. For Python 2 compatibility, I've replaced the default `open` with the Python3 equivalent function from the `io` module.

I'll add this debug functionality to the unit tests while I'm at it.

**Comment by glitchassassin** [comment]
This has been rolled out to Pypi.
