### ISSUE TITLE
I would like to know what the OCR module is planning?

### ISSUE THREAD

**Issue by 23233** [glitchassassin/lackey#94]
this module is important to me ....

**Comment by glitchassassin** [comment]
The main obstacle at the moment is that I have not found any plug-and-play OCR modules on PyPI. They all require an OCR library to be installed manually.

I've begun tinkering with [a Tesseract wrapper](https://github.com/glitchassassin/easy-ocr), but I was having difficulty getting everything to compile correctly and haven't gotten back to it since January.

If you'd like more details, the OCR implementation is being tracked in task #24.

**Comment by glitchassassin** [comment]
Closing this issue.
